# GitHub Actions allows you to build, test, and deploy applications in your language of choice
name: Node CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: 0 0 * * SUN

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [20.x]

    runs-on: ${{ matrix.os }}

    steps:
      # checkout the repo
      - name: Checkout
        uses: actions/checkout@v4

      # use node.js matrix
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      # install dependencies
      - name: Clean install dependencies
        run: yarn install

      # lint files
      - name: Lint files
        run: yarn run lint
        env:
          CI: true

      # test files
      - name: Test files
        run: yarn run test
        env:
          CI: true
